id: IB8E5D948
legacy_id: P000395
ocr_import_info:
  bdrc_scan_id: W1KG13759
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T21:00:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T04:39:15.424901+00:00'
last_modified: 2022-08-27 12:50:40.173596
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13759
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13759
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། གྲགས་པ་བཤད་སྒྲུབ། ༼གློག་ཀླད་པར་མ།༽
  author: ཅོ་ནེ་གྲགས་པ་བཤད་སྒྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9495808698703762
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG15436:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15436
      total_pages: 524
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1KG15436.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9635990419313631
    legacy_id: v010
  I1KG15428:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15428
      total_pages: 416
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG15428.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9407671625203473
    legacy_id: v002
  I1KG15440:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15440
      total_pages: 432
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I1KG15440.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9300538513971459
    legacy_id: v014
  I1KG15437:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15437
      total_pages: 380
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1KG15437.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9366457490053833
    legacy_id: v011
  I1KG15438:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15438
      total_pages: 374
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1KG15438.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9650224460349682
    legacy_id: v012
  I1KG15439:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15439
      total_pages: 432
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1KG15439.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9386915648795437
    legacy_id: v013
  I1KG15431:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15431
      total_pages: 464
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG15431.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.939087561687951
    legacy_id: v005
  I1KG15434:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15434
      total_pages: 460
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG15434.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9627986035239174
    legacy_id: v008
  I1KG15427:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15427
      total_pages: 480
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15427.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9564166298337347
    legacy_id: v001
  I1KG15435:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15435
      total_pages: 444
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG15435.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9528165502849547
    legacy_id: v009
  I1KG15432:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15432
      total_pages: 380
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG15432.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9555201693095103
    legacy_id: v006
  I1KG15429:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15429
      total_pages: 352
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG15429.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.94403422374135
    legacy_id: v003
  I1KG15430:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15430
      total_pages: 452
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG15430.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9444383588671794
    legacy_id: v004
  I1KG15433:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15433
      total_pages: 439
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG15433.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9590311504566709
    legacy_id: v007
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
