id: IB8E5D948
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T21:07:20+00:00'
last_modified: '2022-06-15T17:46:55.858635+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13759
  title: གསུང་འབུམ། གྲགས་པ་བཤད་སྒྲུབ། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E664:
      image_group_id: I1KG15427
      title: Volume 1 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 480
      order: 1
      base_file: E664.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
